### ISSUE TITLE
teletype screen glitch with up-down combination

### ISSUE THREAD

**Issue by bensteinberg** [tehn/mod#16]
I hit up and down arrows at once by mistake, and saw the glitch below on my Teletype:

![20150708_143314](https://cloud.githubusercontent.com/assets/3776423/8578761/a34d1574-257e-11e5-88d9-a1fc1469af02.jpg)

Hitting Enter adds another line of glitch, but then an up-arrow gets back the command I meant to retrieve, and another Enter cleans up the screen entirely.

This is a very minor issue -- does not affect functionality -- but I thought you might want to know about it. Please let me know if you have any questions.

**Comment by tehn** [comment]
thanks for the heads up. this is an out-of-bounds error that i thought i
caught already.

fyi up/down are correct keys for navigating history.

did the error happen immediately on startup or later in operation?

**Comment by bensteinberg** [comment]
I can't get it to happen immediately on startup, or after a single command at the live screen. I can't tell yet when it becomes possible, but will keep an eye out.

**Comment by bensteinberg** [comment]
I noticed this and https://github.com/tehn/mod/issues/17 around the same time, and it's possible the code I describe there is what's getting the module into this state, too.

**Comment by tehn** [comment]
a9a9158..c65b167
