### ISSUE TITLE
teletype stops reading IN and PARAM

### ISSUE THREAD

**Issue by bensteinberg** [tehn/mod#17]
After some amount of playing, I can no longer get new values from IN and PARAM.  Powering down and repowering the case solves the problem.  I'm not sure if the effect comes after a certain amount of time, or after some particular coding.  Sorry, this is a pretty bad bug report, but I hope to be able to add more later.  For what it's worth, I noticed this while working on a scene that polls IN and/or PARAM in the M script, then updates M, something like:

    T DIV PARAM 16
    M T
    TR.PULSE A

**Comment by tehn** [comment]
i've seen this a few times but wasn't able to replicate the issue. will try
my best to track it down. please let me know if you discover repeatable
steps to cause failure.

**Comment by M4R71Ngitub** [comment]
Got the same ug here, PARAM frozes:

"I'm not sure if the effect comes after a certain amount of time, or after some particular coding" => for me it's a coding thing. PARAM freeze in a certain scene whenever i input X DIV PARAM 163.  

" I noticed this while working on a scene that polls IN and/or PARAM in the M script" => I'm not using PARAM or IN in M but using T too:

I:
T 0
M.ACT 1

M:
M 1000
T ADD T 1

**Comment by tehn** [comment]
fixed in v1.1
