### ISSUE TITLE
EXP operator not implemented in teletype

### ISSUE THREAD

**Issue by bensteinberg** [tehn/mod#22]
Although

    CV 1 EXP V RAND 10
is [in the documentation](http://monome.org/docs/modular/teletype/), it doesn't work, and `EXP` isn't in teletype.c.

**Comment by tehn** [comment]
thank you for catching this!

**Comment by bensteinberg** [comment]
You're welcome! Thanks for all your work. Let me know if there's anything in particular you'd like tested, or if you have any preference about how to submit issues.

**Comment by tehn** [comment]
c65b167..0ebee58
