### ISSUE TITLE
SCALE operator

### ISSUE THREAD

**Issue by tehn** [tehn/mod#32]
SCALE A B X Y I

A to B is the input range, X to Y is the output range, I is the value to scale.

**Comment by findzen** [comment]
This would be very useful. Sounds a bit like how the scale device works in Ableton. Could this be used as a foundation for implementing musical scale maps? Semitone note lookup is nice, but it would be amazing to be able to have scale lookup tables, something like `C.MINOR 3`, `Db.LYDIAN 7`, etc.

**Comment by findzen** [comment]
A simple version of [Teoria](https://github.com/saebekassebil/teoria) perhaps? I would love to help implement this but I'm more of a Ruby/Javascript guy.

**Comment by tehn** [comment]
380bd6e..20d2209
