### ISSUE TITLE
JI operator

### ISSUE THREAD

**Issue by trentgill** [tehn/mod#33]
JI N D

Just Intonation helper operator.
N is numerator, D is denominator.

Performs a fractional division of N / D. Returns a value normalized between `V 0` and `V 1`.
The output is designed to attach directly to a `CV x` output, normalized for 1V/Octave tuning.
'Root note' would be implemented by use of the `CV.OFF` function, which could itself use another `JI` operator if the root should move in just steps as well.

As is typical in Just intonation systems, notes are always calculated in the first octave. Using a simple `ADD V x JI ...` would allow specific octaves to be set per note.

**Comment by trentgill** [comment]
The functionality is already largely possible by using something like:
`DIV MUL V 1 N D`

This works fine for numerators up to ~80 provided the numerator is larger than the denominator. The proposed operator would simplify the process by allowing fractions less than 1 (eg. 3/4) by transposing it into 3/2.

Furthermore, the operator would improve accuracy of larger integer fractions by using a lookup table rather than the `V 1` magic number.

**Comment by trentgill** [comment]
Simplifying from the above the following would work up to numerators of 10:
`DIV V N D`

As an interim / alternative solution, the `V` lookup table could be extended beyond `V 10` up to the numerical limit of signed 16bit: `V 80`. Thus, `V` could be used a standardized identity for fractional numbers. It would be accurate enough for numbers down to 1/24 (or a quarter tone).

///

To clarify - the `JI` operator would be particularly useful because it normalizes the output of any given input fraction to a number between `V 0` and `V 1` by means of multiplying/dividing by factors of 2.

It would also have some kind of dynamic range calibration such that small fractions are calculated more accurately (7/6), while large integer fractions avoid saturation, particularly when using pythagorean tuning (1024/729).

11-limit JI should be supported (max ints: 20/11), though 15-limit would be preferable (max ints: 28/15). See https://en.wikipedia.org/wiki/Tonality_diamond.

**Comment by tehn** [comment]
this will work easily with any numerator and denominator combination at high resolution. limit of resolution will be the output range for 1v

**Comment by tehn** [comment]
2be8da4..a275e5c
