### ISSUE TITLE
TELETYPE - INIT script execution failure with keyboard-less scene selection

### ISSUE THREAD

**Issue by M4R71Ngitub** [tehn/mod#35]
INIT script fail to execute with the scene recall button. 

BUG TEST SCENE:

I:
M.ACT 1
T 0

M:
M 1000
T ADD T 1

result: T never resets to 0 when changing scene and coming back to the test one.

**Comment by tehn** [comment]
confirmed this bug. thank you for reporting. will get it fixed in the next
rev.

**Comment by tehn** [comment]
653096e..caa3f28
