### ISSUE TITLE
White whale pattern changes

### ISSUE THREAD

**Issue by findzen** [tehn/mod#53]
Apologies if this is due to my ignorance, but I've found that when changing between patterns of different links there is a gap in playback.

For instance, pattern 1 has all 16 steps programmed, whereas pattern 2 only has 8. Depending on the position of the playhead when switching from pattern 1 to pattern 2, pattern 2 may start playing outside its loop points where there is no note/trigger data, resulting in an undesirable gap.

It would be nice if, when switching patterns, it respected the loop points and did not attempt to start playback from outside them.

**Comment by tehn** [comment]
this is true. the workaround is to use a queued pattern change by holding
ALT. this will switch patterns when the current pattern loops hits start
again.

your point is a good one, though. but the default behavior for out-of-loop
is awkward. it doesn't seem right to just reset to start for phase reasons.
we could do a step position wrap, which might sound/work correctly. what do
you think?

**Comment by findzen** [comment]
Yes that sounds like it could work. So that would mean if we have a 16 step pattern at position 10 and trigger an 8 step pattern, it would start at position 3?

**Comment by tehn** [comment]
moved https://github.com/monome/whitewhale/issues/2
